public class ReportData 
{
	public Integer newAttendees {get;set;}
	public Integer newMales {get;set;}
	public Integer newFemales {get;set;}
	public Integer totalClients {get;set;}
	public Integer totalMales {get;set;}
	public Integer totalFemales {get;set;}
	public Integer age1 {get;set;}
	public Integer age2 {get;set;}
	public Integer age3 {get;set;}
	public Integer age4 {get;set;}
	public Integer age5 {get;set;}
	public Integer age6 {get;set;}
	public Integer age7 {get;set;}
	public Integer age8 {get;set;}
	public Integer age9 {get;set;}
	public Integer ageNone {get;set;}
	public Integer Amphetamines {get;set;}
	public Integer Heroin {get;set;}
	public Integer Cocaine {get;set;}
	public Integer Benzodiazepines {get;set;}
	public Integer Legalhighs {get;set;}
	public Integer PrescribedMethadone {get;set;}
	public Integer StreetMethadone {get;set;}
	public Integer Ecstasy {get;set;}
	public Integer Cannabis {get;set;}
	public Integer Crackcocaine {get;set;}
	public Integer Alcohol {get;set;}
	public Integer CrystalMeth {get;set;}
	public Integer OTC {get;set;}
	public Integer Other {get;set;}
	public Integer CarePlansInPlace {get;set;}
	public Integer CarePlansCreated {get;set;}
	public Integer CarePlansReviewed {get;set;}
	public Integer CarePlansCompleted {get;set;}
	public Integer AdviceAndSupport {get;set;}
	public Integer One2One {get;set;}
	public Integer one2oneClients {get;set;}
	public Integer phoneSupportCalls {get;set;}
	public Integer familySupportSessions {get;set;}
	public Integer FamilySupportGroupSessions {get;set;}
	public Integer FamilySupportGroupClients {get;set;}
	public Integer NewFamilySupportGroups {get;set;}
	public Integer ClosedFamilySupportGroups {get;set;}
	public Integer NewFamilySupportGroupClients {get;set;}
	public Integer AftercareSupportGroupSessions {get;set;}
	public Integer AftercareSupportGroupClients {get;set;}
	
	public Integer RelapsePrevention {get;set;}
	public Integer Laundry {get;set;}
	public Integer Woodwork {get;set;}
	public Integer Personal_Care {get;set;}
	public Integer Stabilisation_group {get;set;}
	public Integer Showers {get;set;}
	public Integer Nutrition {get;set;}
	public Integer PhoneCallsOut {get;set;}
	public Integer Computer {get;set;}
	public Integer LiteracySupport {get;set;}
	public Integer PlacementfromNLN {get;set;}
	public Integer PlacementfromAIT {get;set;}
	public Integer ArtsandCraftsTraining {get;set;}
	public Integer CookeryClasses {get;set;}
	public Integer HorticulturalClasses {get;set;}
	public Integer totalReferralsIn {get;set;}
	public Integer maleReferralsIn {get;set;}
	public Integer femaleReferralsIn {get;set;}
	public Integer CommunityDetoxProgramme {get;set;}
	public Integer DetoxResidentialSetting {get;set;}
	public Integer CommunityGP {get;set;}
	public Integer CADS{get;set;}
	public Integer SteppingOutProject{get;set;}
	public Integer ComplimentaryTherapies {get;set;}
	public Integer VEC {get;set;}
	public Integer SocialWelfare {get;set;}
	public Integer TFEProject {get;set;}
	public Integer HousingOfficer {get;set;}
	public Integer AnaLiffeyDrugProject {get;set;}
	public Integer StMarthasLongford {get;set;}
	public Integer OtherMQIService{get;set;}
	public Integer OtherSIMONCommunity {get;set;}
	public Integer totalReferralsOut {get;set;} 
	public Integer maleReferralsOut {get;set;} 
	public Integer femaleReferralsOut {get;set;}
	public Integer totalVisits {get;set;}
	
	public Integer RefOutSocialOccupationalreintegration {get;set;}
	public Integer RefOutCADSHSE {get;set;}
	public Integer RefOutSIMONCommunity  {get;set;}
	public Integer RefOutAftercareMQIOutreach  {get;set;}
	public Integer RefOutTravellerMediation  {get;set;}
	public Integer RefOutTravellerCommunityDevelopment  {get;set;}
	public Integer RefOutSuicideAwarenessOfficer  {get;set;}
	public Integer RefOutOtherrefuge  {get;set;}
	public Integer RefOutDetoxProgramme  {get;set;}
	public Integer RefOutCommunityGP  {get;set;}
	public Integer RefOutMedicationfreetherapy  {get;set;}
	public Integer RefOutMethadone  {get;set;}
	public Integer RefOutTravellerHealthUnit  {get;set;}
	public Integer RefOutComplimentaryTherapies  {get;set;}
	public Integer RefOutAnaLiffeyDrugProject  {get;set;}
	public Integer RefOutCommunityDetox  {get;set;} 
	
	public Integer RefOutChildren  {get;set;} 
	public Integer RefOutMidlands {get;set;} 
	public Integer RefOutYouth  {get;set;} 
	public Integer RefOutMABs  {get;set;} 
	public Integer RefOutFamilySupport  {get;set;} 
	public Integer RefOutFamilyResource  {get;set;} 
	public Integer RefOutFamilyMediation  {get;set;} 
	public Integer RefOutFamilyTherapist {get;set;} 
	public Integer RefOutCounselling {get;set;} 
	
	
	public Integer AdvocacyCADSHSEAdvocacy  {get;set;}
	public Integer AdvocacyFurtherEducation  {get;set;}
	public Integer AdvocacyHousing  {get;set;}
	public Integer AdvocacyOtherClothing  {get;set;}
	public Integer AdvocacyPrison  {get;set;}
	public Integer AdvocacySocialWelfare  {get;set;}
	public Integer AdvocacySVDP  {get;set;}
	public Integer totalAdvocacy {get;set;}
	
	public Integer NXSessions {get;set;}
	public Integer NXClients {get;set;}
	public Integer NXNonClients {get;set;}
	public Integer NXNewClients {get;set;}
	public Integer NX10mls {get;set;}
	public Integer NX5mls {get;set;}
	public Integer NX2mls {get;set;}
	public Integer NXDibs {get;set;}
	public Integer NXMonojets {get;set;}
	public Integer NX1mls {get;set;}
	public Integer NXOranges {get;set;}
	public Integer NXBrowns {get;set;}
	public Integer NXBabyBrowns {get;set;}
	public Integer NXBlues {get;set;}
	public Integer NXGreens {get;set;}
	public Integer NXNeedlesOut {get;set;}
	public Integer NXNeedlesIn {get;set;}
	public Integer NXSharpBinsOut {get;set;}
	public Integer NXSharpBinsIn {get;set;}
	public Integer NXCondoms {get;set;}
	public Integer NXCookpots {get;set;}
	public Integer NXFoilSheets {get;set;}
	public Integer NXWater {get;set;}
	public Integer NXWipes {get;set;}
	public Integer NXTourniquets {get;set;}
		
	
	public Map<String,Integer> clientTypes {get;set;}
	public Map<String,Integer> supports {get;set;}
	public Map<String,Integer> primaryDrugTypes {get;set;}
	public Map<String,Integer> interventionTypes {get;set;}
	public Map<String,Integer> outcomesSelfReports {get;set;}
	public Map<String,Integer> referralsIn {get;set;}
	public Map<String,Integer> one2onesupporttypes {get;set;}
	public Map<String,Integer> phoneSupportReasons {get;set;}
	public Map<String,Integer> legalStatuses {get;set;}
	public Map<String,Integer> interventionReasons {get;set;}
	
	public ReportData ()
	{
		newAttendees = 0;
		newMales = 0;
		newFemales = 0;
		totalClients = 0;
		totalMales = 0;
		totalFemales = 0;
		age1 = 0;
		age2 = 0;
		age3 = 0;
		age4 = 0;
		age5 = 0;
		age6 = 0;
		age7 = 0;
		age8 = 0;
		age9 = 0;
		ageNone = 0;
		Amphetamines = 0;
		Heroin = 0;
		Cocaine = 0;
		Benzodiazepines = 0;
		Legalhighs = 0;
		PrescribedMethadone = 0;
		StreetMethadone = 0;
		Ecstasy = 0;
		Cannabis = 0;
		Crackcocaine = 0;
		Alcohol = 0;
		CrystalMeth = 0;
		OTC = 0;
		Other = 0;
		CarePlansInPlace = 0;
		CarePlansCreated = 0;
		CarePlansReviewed = 0;
		CarePlansCompleted = 0;
		AdviceAndSupport = 0;
		One2One = 0;
		one2oneClients = 0;
		phoneSupportCalls = 0;
		familySupportSessions = 0;
		FamilySupportGroupSessions = 0;
		FamilySupportGroupClients = 0;
		NewFamilySupportGroups = 0;
		ClosedFamilySupportGroups = 0;
		NewFamilySupportGroupClients = 0;
		AftercareSupportGroupSessions = 0;
		AftercareSupportGroupClients = 0;
		RelapsePrevention = 0;
		Laundry = 0;
		Woodwork = 0;
		Personal_Care = 0;
		Stabilisation_group = 0;
		Showers = 0;
		Nutrition = 0;
		PhoneCallsOut = 0;
		Computer = 0;
		LiteracySupport = 0;
		PlacementfromNLN = 0;
		PlacementfromAIT = 0;
		ArtsandCraftsTraining = 0;
		CookeryClasses = 0;
		HorticulturalClasses = 0;
		totalReferralsIn = 0;
		maleReferralsIn = 0;
		femaleReferralsIn = 0;
		CommunityDetoxProgramme = 0;
		DetoxResidentialSetting = 0;
		CommunityGP = 0;
		CADS= 0;
		SteppingOutProject= 0;
		ComplimentaryTherapies = 0;
		VEC = 0;
		SocialWelfare = 0;
		TFEProject = 0;
		HousingOfficer = 0;
		AnaLiffeyDrugProject = 0;
		StMarthasLongford = 0;
		OtherMQIService= 0;
		OtherSIMONCommunity = 0;
		totalReferralsOut = 0; 
		maleReferralsOut = 0; 
		femaleReferralsOut = 0;
		totalVisits = 0;
		
		RefOutSocialOccupationalreintegration= 0;
		RefOutCADSHSE= 0;
		RefOutSIMONCommunity = 0;
		RefOutAftercareMQIOutreach = 0;
		RefOutTravellerMediation = 0;
		RefOutTravellerCommunityDevelopment = 0;
		RefOutSuicideAwarenessOfficer = 0;
		RefOutOtherrefuge = 0;
		RefOutDetoxProgramme = 0;
		RefOutCommunityGP = 0;
		RefOutMedicationfreetherapy = 0;
		RefOutMethadone = 0;
		RefOutTravellerHealthUnit = 0;
		RefOutComplimentaryTherapies = 0;
		RefOutAnaLiffeyDrugProject = 0;
		RefOutCommunityDetox = 0; 
		
		RefOutChildren = 0; 
		RefOutMidlands = 0;
		RefOutYouth = 0; 
		RefOutMABs = 0; 
		RefOutFamilySupport = 0;
		RefOutFamilyResource = 0;
		RefOutFamilyMediation = 0;
		RefOutFamilyTherapist = 0; 
		RefOutCounselling = 0;
		
		AdvocacyCADSHSEAdvocacy = 0;
		AdvocacyFurtherEducation = 0;
		AdvocacyHousing = 0;
		AdvocacyOtherClothing = 0;
		AdvocacyPrison = 0;
		AdvocacySocialWelfare = 0;
		AdvocacySVDP = 0;
		totalAdvocacy = 0;
		
		NXSessions = 0;
		NXClients = 0;
		NXNonClients = 0;
		NXNewClients = 0;
		NX10mls = 0;
		NX5mls = 0;
		NX2mls = 0;
		NXDibs = 0;
		NXMonojets = 0;
		NX1mls = 0;
		NXOranges = 0;
		NXBrowns = 0;
		NXBabyBrowns = 0;
		NXBlues = 0;
		NXGreens = 0;
		NXNeedlesOut = 0;
		NXNeedlesIn = 0;
		NXSharpBinsOut = 0;
		NXSharpBinsIn = 0;
		NXCondoms = 0;
		NXCookpots  = 0;
		NXFoilSheets  = 0;
		NXWater = 0;
		NXWipes = 0;
		NXTourniquets = 0;
		
		clientTypes = new Map<String, Integer>();
		supports = new Map<String, Integer>();
		primaryDrugTypes = new Map<String, Integer>();
		interventionTypes = new Map<String, Integer>();
		outcomesSelfReports = new Map<String, Integer>();
		referralsIn = new Map<String,Integer> ();
		one2onesupporttypes = new Map<String,Integer> ();
		phonesupportreasons = new Map<String,Integer> ();
		legalStatuses = new Map<String, Integer>();
		interventionReasons = new Map<String, Integer>();
	}
	
	public void accumulateNXReferralOutStats (aggregateResult ar)
	{
		RefOutCommunityDetox += (Integer)ar.get('communityDetox');
		RefOutDetoxProgramme += (Integer)ar.get('residentialDetox');
		RefOutCommunityGP += (Integer)ar.get('gp');
		RefOutCADSHSE += (Integer)ar.get('CADS');
		RefOutMedicationfreetherapy += (Integer)ar.get('meds');
		RefOutComplimentaryTherapies += (Integer)ar.get('comp');
		RefOutSocialOccupationalreintegration += (Integer)ar.get('social');
		RefOutOtherrefuge += (Integer)ar.get('otherOut');
		RefOutAftercareMQIOutreach += (Integer)ar.get('otherMQI');
	}
	
	public void calculateNXMaterialsStats (aggregateResult ar)
	{
		if (ar == null) return;
		
		NXSessions = (Integer)ar.get('sessions');
		NX10mls = (Integer)(Decimal)(ar.get('x10mls') != null?ar.get('x10mls'):0);
		NX5mls = (Integer)(Decimal)(ar.get('x5mls') != null?ar.get('x5mls'):0);
		NX2mls = (Integer)(Decimal)(ar.get('x2mls') != null?ar.get('x2mls'):0);
		NXDibs = (Integer)(Decimal)(ar.get('dibs') != null?ar.get('dibs'):0);
		NXMonojets = (Integer)(Decimal)(ar.get('x1ml') != null?ar.get('x1ml'):0);
		NX1mls = (Integer)(Decimal)(ar.get('omni') != null?ar.get('omni'):0);
		NXOranges = (Integer)(Decimal)(ar.get('orange') != null?ar.get('orange'):0);
		NXBrowns = (Integer)(Decimal)(ar.get('brown') != null?ar.get('brown'):0);
		NXBabyBrowns = (Integer)(Decimal)(ar.get('babybrown') != null?ar.get('babybrown'):0);
		NXBlues = (Integer)(Decimal)(ar.get('blue') != null?ar.get('blue'):0);
		NXGreens = (Integer)(Decimal)(ar.get('green') != null?ar.get('green'):0);
		NXNeedlesOut = (Integer)(Decimal)(ar.get('needlesOut') != null?ar.get('needlesOut'):0);
		NXNeedlesIn = (Integer)(Decimal)(ar.get('needlesIn') != null?ar.get('needlesIn'):0);
		NXSharpBinsOut = (Integer)(Decimal)(ar.get('binsOut') != null?ar.get('binsOut'):0);
		NXSharpBinsIn = (Integer)(Decimal)(ar.get('binsIn') != null?ar.get('binsIn'):0);
		NXCondoms = (Integer)(Decimal)(ar.get('condoms') != null?ar.get('condoms'):0);
		NXCookpots  = (Integer)(Decimal)(ar.get('pots') != null?ar.get('pots'):0);
		NXFoilSheets  = (Integer)(Decimal)(ar.get('foils') != null?ar.get('foils'):0);
		NXWater = (Integer)(Decimal)(ar.get('water') != null?ar.get('water'):0);
		NXWipes = (Integer)(Decimal)(ar.get('wipes') != null?ar.get('wipes'):0);
		NXTourniquets = (Integer)(Decimal)(ar.get('tourniquets') != null?ar.get('tourniquets'):0);
	}
}